ALTER TABLE teams 
  DROP COLUMN IF EXISTS created_by VARCHAR(255),
  DROP COLUMN IF EXISTS updated_by VARCHAR(255),
  DROP COLUMN IF EXISTS deleted_by VARCHAR(255);

ALTER TABLE players 
  DROP COLUMN IF EXISTS created_by VARCHAR(255),
  DROP COLUMN IF EXISTS updated_by VARCHAR(255),
  DROP COLUMN IF EXISTS deleted_by VARCHAR(255);

ALTER TABLE matches 
  DROP COLUMN IF EXISTS created_by VARCHAR(255),
  DROP COLUMN IF EXISTS updated_by VARCHAR(255),
  DROP COLUMN IF EXISTS deleted_by VARCHAR(255);

ALTER TABLE goals 
  DROP COLUMN IF EXISTS created_by VARCHAR(255),
  DROP COLUMN IF EXISTS updated_by VARCHAR(255),
  DROP COLUMN IF EXISTS deleted_by VARCHAR(255);

ALTER TABLE match_results 
  DROP COLUMN IF EXISTS created_by VARCHAR(255);