// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type PlayerPosition string

const (
	PlayerPositionS PlayerPosition = "S"
	PlayerPositionM PlayerPosition = "M"
	PlayerPositionB PlayerPosition = "B"
	PlayerPositionK PlayerPosition = "K"
)

func (e *PlayerPosition) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PlayerPosition(s)
	case string:
		*e = PlayerPosition(s)
	default:
		return fmt.Errorf("unsupported scan type for PlayerPosition: %T", src)
	}
	return nil
}

type NullPlayerPosition struct {
	PlayerPosition PlayerPosition `json:"player_position"`
	Valid          bool           `json:"valid"` // Valid is true if PlayerPosition is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPlayerPosition) Scan(value interface{}) error {
	if value == nil {
		ns.PlayerPosition, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PlayerPosition.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPlayerPosition) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PlayerPosition), nil
}

type Goal struct {
	ID         pgtype.UUID        `json:"id"`
	MatchID    pgtype.UUID        `json:"match_id"`
	PlayerID   pgtype.UUID        `json:"player_id"`
	GoalMinute pgtype.Text        `json:"goal_minute"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	IsDeleted  pgtype.Bool        `json:"is_deleted"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Match struct {
	ID         pgtype.UUID        `json:"id"`
	MatchDate  pgtype.Date        `json:"match_date"`
	MatchTime  pgtype.Time        `json:"match_time"`
	HomeTeamID pgtype.UUID        `json:"home_team_id"`
	AwayTeamID pgtype.UUID        `json:"away_team_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
	IsDeleted  pgtype.Bool        `json:"is_deleted"`
	DeletedAt  pgtype.Timestamptz `json:"deleted_at"`
}

type Player struct {
	ID           pgtype.UUID        `json:"id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Name         string             `json:"name"`
	HeightCm     pgtype.Numeric     `json:"height_cm"`
	WeightKg     pgtype.Numeric     `json:"weight_kg"`
	Position     PlayerPosition     `json:"position"`
	JerseyNumber int16              `json:"jersey_number"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsDeleted    pgtype.Bool        `json:"is_deleted"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type Team struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Logo        pgtype.Text        `json:"logo"`
	FoundedYear pgtype.Text        `json:"founded_year"`
	Address     string             `json:"address"`
	City        string             `json:"city"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	IsDeleted   pgtype.Bool        `json:"is_deleted"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}
