// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckTeamExisits(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	CreateGoals(ctx context.Context, arg *CreateGoalsParams) (pgtype.UUID, error)
	CreateMatches(ctx context.Context, arg *CreateMatchesParams) (pgtype.UUID, error)
	CreatePlayerTeam(ctx context.Context, arg *CreatePlayerTeamParams) (pgtype.UUID, error)
	CreateTeam(ctx context.Context, arg *CreateTeamParams) (pgtype.UUID, error)
	DeleteGoals(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	DeleteMatch(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	DeletePlayer(ctx context.Context, id pgtype.UUID) (*Player, error)
	GetListMatch(ctx context.Context, arg *GetListMatchParams) ([]*GetListMatchRow, error)
	GetListMatchGoals(ctx context.Context, matchID pgtype.UUID) ([]*GetListMatchGoalsRow, error)
	GetListPlayer(ctx context.Context) ([]*GetListPlayerRow, error)
	GetListPlayerTeam(ctx context.Context, teamID pgtype.UUID) ([]*GetListPlayerTeamRow, error)
	GetListTeams(ctx context.Context) ([]*GetListTeamsRow, error)
	GetPlayerDetail(ctx context.Context, id pgtype.UUID) (*GetPlayerDetailRow, error)
	GetTeamDetail(ctx context.Context, id pgtype.UUID) (*Team, error)
	MatchFullTime(ctx context.Context, matchID pgtype.UUID) (pgtype.UUID, error)
	RescheduleMatch(ctx context.Context, arg *RescheduleMatchParams) (pgtype.UUID, error)
	SoftDeleteTeams(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error)
	UpdatePlayers(ctx context.Context, arg *UpdatePlayersParams) (*Player, error)
	UpdateTeams(ctx context.Context, arg *UpdateTeamsParams) (*Team, error)
}

var _ Querier = (*Queries)(nil)
