// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePlayerTeam(ctx context.Context, arg *CreatePlayerTeamParams) (pgtype.UUID, error)
	CreateTeam(ctx context.Context, arg *CreateTeamParams) (pgtype.UUID, error)
	GetListTeams(ctx context.Context) ([]*GetListTeamsRow, error)
	SoftDeleteTeams(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
