// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkTeamExisits = `-- name: CheckTeamExisits :one
SELECT id FROM teams WHERE id = $1
`

func (q *Queries) CheckTeamExisits(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, checkTeamExisits, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const createAdminAccount = `-- name: CreateAdminAccount :one
INSERT INTO admin_account (
  username, password
) VALUES (
  $1, $2
) RETURNING id
`

type CreateAdminAccountParams struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

func (q *Queries) CreateAdminAccount(ctx context.Context, arg *CreateAdminAccountParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createAdminAccount, arg.Username, arg.Password)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createGoals = `-- name: CreateGoals :one
INSERT INTO goals(
  match_id, player_id, goal_minute
) 
SELECT
  m.id,
  p.id,
  $1
FROM matches m
JOIN players p ON p.id = $2 
WHERE m.id = $3
  AND m.is_deleted = false
  AND p.is_deleted = false 
  AND (m.home_team_id = p.team_id OR m.away_team_id = p.team_id)
RETURNING id
`

type CreateGoalsParams struct {
	GoalMinute pgtype.Text `json:"goal_minute"`
	PlayerID   pgtype.UUID `json:"player_id"`
	MatchID    pgtype.UUID `json:"match_id"`
}

func (q *Queries) CreateGoals(ctx context.Context, arg *CreateGoalsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createGoals, arg.GoalMinute, arg.PlayerID, arg.MatchID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createMatches = `-- name: CreateMatches :one
INSERT INTO matches(
  match_date, match_time, home_team_id, away_team_id
) VALUES (
  $1, $2, $3, $4
) RETURNING id
`

type CreateMatchesParams struct {
	MatchDate  pgtype.Date `json:"match_date"`
	MatchTime  pgtype.Time `json:"match_time"`
	HomeTeamID pgtype.UUID `json:"home_team_id"`
	AwayTeamID pgtype.UUID `json:"away_team_id"`
}

func (q *Queries) CreateMatches(ctx context.Context, arg *CreateMatchesParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createMatches,
		arg.MatchDate,
		arg.MatchTime,
		arg.HomeTeamID,
		arg.AwayTeamID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createPlayerTeam = `-- name: CreatePlayerTeam :one
INSERT INTO players (
  team_id, name, height_cm, weight_kg, position, jersey_number
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreatePlayerTeamParams struct {
	TeamID       pgtype.UUID    `json:"team_id"`
	Name         string         `json:"name"`
	HeightCm     pgtype.Numeric `json:"height_cm"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Position     PlayerPosition `json:"position"`
	JerseyNumber int16          `json:"jersey_number"`
}

func (q *Queries) CreatePlayerTeam(ctx context.Context, arg *CreatePlayerTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPlayerTeam,
		arg.TeamID,
		arg.Name,
		arg.HeightCm,
		arg.WeightKg,
		arg.Position,
		arg.JerseyNumber,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
  name, logo, founded_year, address, city
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id
`

type CreateTeamParams struct {
	Name        string      `json:"name"`
	Logo        pgtype.Text `json:"logo"`
	FoundedYear pgtype.Text `json:"founded_year"`
	Address     string      `json:"address"`
	City        string      `json:"city"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg *CreateTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Logo,
		arg.FoundedYear,
		arg.Address,
		arg.City,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const deleteGoals = `-- name: DeleteGoals :one
UPDATE goals
SET
  is_deleted = true,
  deleted_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id
`

func (q *Queries) DeleteGoals(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteGoals, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const deleteMatch = `-- name: DeleteMatch :one
UPDATE matches
SET 
  is_deleted = true,
  deleted_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id
`

func (q *Queries) DeleteMatch(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteMatch, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const deletePlayer = `-- name: DeletePlayer :one
UPDATE players
SET 
  is_deleted = true,
  deleted_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id, team_id, name, height_cm, weight_kg, position, jersey_number, created_at, updated_at, is_deleted, deleted_at
`

func (q *Queries) DeletePlayer(ctx context.Context, id pgtype.UUID) (*Player, error) {
	row := q.db.QueryRow(ctx, deletePlayer, id)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.HeightCm,
		&i.WeightKg,
		&i.Position,
		&i.JerseyNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return &i, err
}

const getAdmingByUsername = `-- name: GetAdmingByUsername :one
SELECT username, password, id
FROM admin_account
WHERE username = $1 AND is_deleted = false
`

type GetAdmingByUsernameRow struct {
	Username string      `json:"username"`
	Password string      `json:"password"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetAdmingByUsername(ctx context.Context, username string) (*GetAdmingByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getAdmingByUsername, username)
	var i GetAdmingByUsernameRow
	err := row.Scan(&i.Username, &i.Password, &i.ID)
	return &i, err
}

const getListMatch = `-- name: GetListMatch :many
SELECT
  m.id,
  m.match_date,
  m.match_time,
  m.home_team_id,
  m.away_team_id,
  home.name as home_team_name,
  home.logo as home_logo,
  away.name as away_team_name,
  away.logo as away_logo,
  mr.status,
  mr.home_score,
  mr.away_score,
  p.id as player_id,
  p.name as player_name,
  p.jersey_number as player_number,
  p.team_id as player_team_id,
  g.id as goal_id,
  g.goal_minute
FROM matches m
LEFT JOIN teams home ON m.home_team_id = home.id
LEFT JOIN teams away ON m.away_team_id = away.id
LEFT JOIN match_results mr ON mr.id = m.id
LEFT JOIN goals g ON g.match_id = m.id and g.is_deleted = false
LEFT JOIN players p ON p.id = g.player_id
WHERE m.is_deleted = false
  AND (
    ($1::uuid IS NULL OR home_team_id = $1::uuid) OR 
    ($2::uuid IS NULL OR away_team_id = $2::uuid)
  )
  AND home.is_deleted = false
  AND away.is_deleted = false
  AND (
    $3::text IS NULL OR
    ($3::text = 'scheduled' AND mr.id IS NULL) OR
    ($3::text = 'result' AND mr.id IS NOT NULL)
  )
ORDER BY m.match_date ASC, m.match_time ASC, g.goal_minute ASC
`

type GetListMatchParams struct {
	HomeTeamID pgtype.UUID `json:"home_team_id"`
	AwayTeamID pgtype.UUID `json:"away_team_id"`
	FilterType pgtype.Text `json:"filter_type"`
}

type GetListMatchRow struct {
	ID           pgtype.UUID `json:"id"`
	MatchDate    pgtype.Date `json:"match_date"`
	MatchTime    pgtype.Time `json:"match_time"`
	HomeTeamID   pgtype.UUID `json:"home_team_id"`
	AwayTeamID   pgtype.UUID `json:"away_team_id"`
	HomeTeamName pgtype.Text `json:"home_team_name"`
	HomeLogo     pgtype.Text `json:"home_logo"`
	AwayTeamName pgtype.Text `json:"away_team_name"`
	AwayLogo     pgtype.Text `json:"away_logo"`
	Status       pgtype.Int2 `json:"status"`
	HomeScore    pgtype.Int2 `json:"home_score"`
	AwayScore    pgtype.Int2 `json:"away_score"`
	PlayerID     pgtype.UUID `json:"player_id"`
	PlayerName   pgtype.Text `json:"player_name"`
	PlayerNumber pgtype.Int2 `json:"player_number"`
	PlayerTeamID pgtype.UUID `json:"player_team_id"`
	GoalID       pgtype.UUID `json:"goal_id"`
	GoalMinute   pgtype.Text `json:"goal_minute"`
}

func (q *Queries) GetListMatch(ctx context.Context, arg *GetListMatchParams) ([]*GetListMatchRow, error) {
	rows, err := q.db.Query(ctx, getListMatch, arg.HomeTeamID, arg.AwayTeamID, arg.FilterType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetListMatchRow{}
	for rows.Next() {
		var i GetListMatchRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchDate,
			&i.MatchTime,
			&i.HomeTeamID,
			&i.AwayTeamID,
			&i.HomeTeamName,
			&i.HomeLogo,
			&i.AwayTeamName,
			&i.AwayLogo,
			&i.Status,
			&i.HomeScore,
			&i.AwayScore,
			&i.PlayerID,
			&i.PlayerName,
			&i.PlayerNumber,
			&i.PlayerTeamID,
			&i.GoalID,
			&i.GoalMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListMatchGoals = `-- name: GetListMatchGoals :many
SELECT
  g.id,
  g.match_id,
  home.id as home_team_id,
  home.name as home_team_name,
  away.id as away_team_id,
  away.name as away_team_name,
  g.player_id,
  p.name as player_name,
  p.jersey_number as jersey_number,
  t.id as team_id,
  t.name as team_name,
  g.goal_minute
FROM goals g
JOIN matches m ON m.id = g.match_id
JOIN players p ON p.id = g.player_id
JOIN teams t ON t.id = p.team_id
LEFT JOIN teams home ON m.home_team_id = home.id
LEFT JOIN teams away ON m.away_team_id = away.id
WHERE g.match_id = $1 AND g.is_deleted = false
ORDER BY g.created_at ASC
`

type GetListMatchGoalsRow struct {
	ID           pgtype.UUID `json:"id"`
	MatchID      pgtype.UUID `json:"match_id"`
	HomeTeamID   pgtype.UUID `json:"home_team_id"`
	HomeTeamName pgtype.Text `json:"home_team_name"`
	AwayTeamID   pgtype.UUID `json:"away_team_id"`
	AwayTeamName pgtype.Text `json:"away_team_name"`
	PlayerID     pgtype.UUID `json:"player_id"`
	PlayerName   string      `json:"player_name"`
	JerseyNumber int16       `json:"jersey_number"`
	TeamID       pgtype.UUID `json:"team_id"`
	TeamName     string      `json:"team_name"`
	GoalMinute   pgtype.Text `json:"goal_minute"`
}

func (q *Queries) GetListMatchGoals(ctx context.Context, matchID pgtype.UUID) ([]*GetListMatchGoalsRow, error) {
	rows, err := q.db.Query(ctx, getListMatchGoals, matchID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetListMatchGoalsRow{}
	for rows.Next() {
		var i GetListMatchGoalsRow
		if err := rows.Scan(
			&i.ID,
			&i.MatchID,
			&i.HomeTeamID,
			&i.HomeTeamName,
			&i.AwayTeamID,
			&i.AwayTeamName,
			&i.PlayerID,
			&i.PlayerName,
			&i.JerseyNumber,
			&i.TeamID,
			&i.TeamName,
			&i.GoalMinute,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListPlayer = `-- name: GetListPlayer :many
SELECT 
  p.id as id,
  p.name,
  p.position,
  p.jersey_number,
  t.id as team_id,
  t.name as team_name
FROM players p
LEFT JOIN teams t ON p.team_id = t.id
WHERE p.is_deleted = false
  AND t.is_deleted = false
ORDER BY p.created_at ASC
`

type GetListPlayerRow struct {
	ID           pgtype.UUID    `json:"id"`
	Name         string         `json:"name"`
	Position     PlayerPosition `json:"position"`
	JerseyNumber int16          `json:"jersey_number"`
	TeamID       pgtype.UUID    `json:"team_id"`
	TeamName     pgtype.Text    `json:"team_name"`
}

func (q *Queries) GetListPlayer(ctx context.Context) ([]*GetListPlayerRow, error) {
	rows, err := q.db.Query(ctx, getListPlayer)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetListPlayerRow{}
	for rows.Next() {
		var i GetListPlayerRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Position,
			&i.JerseyNumber,
			&i.TeamID,
			&i.TeamName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListPlayerTeam = `-- name: GetListPlayerTeam :many
SELECT id, team_id, name, position, jersey_number
FROM players
WHERE team_id = $1 AND is_deleted = false
ORDER BY jersey_number ASC
`

type GetListPlayerTeamRow struct {
	ID           pgtype.UUID    `json:"id"`
	TeamID       pgtype.UUID    `json:"team_id"`
	Name         string         `json:"name"`
	Position     PlayerPosition `json:"position"`
	JerseyNumber int16          `json:"jersey_number"`
}

func (q *Queries) GetListPlayerTeam(ctx context.Context, teamID pgtype.UUID) ([]*GetListPlayerTeamRow, error) {
	rows, err := q.db.Query(ctx, getListPlayerTeam, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetListPlayerTeamRow{}
	for rows.Next() {
		var i GetListPlayerTeamRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.Name,
			&i.Position,
			&i.JerseyNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListTeams = `-- name: GetListTeams :many
SELECT id, name, logo, founded_year
FROM teams
WHERE is_deleted = false
ORDER BY founded_year DESC
`

type GetListTeamsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Logo        pgtype.Text `json:"logo"`
	FoundedYear pgtype.Text `json:"founded_year"`
}

func (q *Queries) GetListTeams(ctx context.Context) ([]*GetListTeamsRow, error) {
	rows, err := q.db.Query(ctx, getListTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetListTeamsRow{}
	for rows.Next() {
		var i GetListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Logo,
			&i.FoundedYear,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlayerDetail = `-- name: GetPlayerDetail :one
SELECT 
  p.id as id,
  p.name,
  p.position,
  p.jersey_number,
  p.height_cm,
  p.weight_kg,
  t.id as team_id,
  t.name as team_name,
  count(g.id) as goals_count,
  p.created_at,
  p.updated_at,
  p.is_deleted,
  p.deleted_at
FROM players p
LEFT JOIN teams t ON p.team_id = t.id
LEFT JOIN goals g ON g.player_id = p.id AND g.is_deleted = false
WHERE p.id = $1
  AND p.is_deleted = false
  AND t.is_deleted = false
GROUP BY p.id, t.id
ORDER BY p.created_at ASC
`

type GetPlayerDetailRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Position     PlayerPosition     `json:"position"`
	JerseyNumber int16              `json:"jersey_number"`
	HeightCm     pgtype.Numeric     `json:"height_cm"`
	WeightKg     pgtype.Numeric     `json:"weight_kg"`
	TeamID       pgtype.UUID        `json:"team_id"`
	TeamName     pgtype.Text        `json:"team_name"`
	GoalsCount   int64              `json:"goals_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	IsDeleted    pgtype.Bool        `json:"is_deleted"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetPlayerDetail(ctx context.Context, id pgtype.UUID) (*GetPlayerDetailRow, error) {
	row := q.db.QueryRow(ctx, getPlayerDetail, id)
	var i GetPlayerDetailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Position,
		&i.JerseyNumber,
		&i.HeightCm,
		&i.WeightKg,
		&i.TeamID,
		&i.TeamName,
		&i.GoalsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return &i, err
}

const getTeamDetail = `-- name: GetTeamDetail :one
SELECT id, name, logo, founded_year, address, city, created_at, updated_at, is_deleted, deleted_at FROM teams
WHERE id = $1 AND is_deleted = false
`

func (q *Queries) GetTeamDetail(ctx context.Context, id pgtype.UUID) (*Team, error) {
	row := q.db.QueryRow(ctx, getTeamDetail, id)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.FoundedYear,
		&i.Address,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return &i, err
}

const matchFullTime = `-- name: MatchFullTime :one
WITH match_info AS (
  SELECT ma.id as match_id, home_team_id, away_team_id
  FROM matches ma
  WHERE ma.id = $1
),
goals_count AS (
  SELECT
    m.match_id,
    COALESCE(SUM(CASE WHEN p.team_id = m.home_team_id THEN 1 ELSE 0 END), 0) AS home_score,
    COALESCE(SUM(CASE WHEN p.team_id = m.away_team_id THEN 1 ELSE 0 END), 0) AS away_score
  FROM match_info m
  LEFT JOIN goals g ON g.match_id = m.match_id and g.is_deleted = false
  LEFT JOIN players p ON p.id = g.player_id
  GROUP BY m.match_id
)
INSERT INTO match_results(
  id, status, home_score, away_score
)
SELECT
  gc.match_id as id,
  CASE 
      WHEN gc.home_score > gc.away_score THEN 1 
      WHEN gc.home_score < gc.away_score THEN -1
      ELSE 0                            
  END AS status,
  gc.home_score,
  gc.away_score
FROM goals_count gc
ON CONFLICT (id) 
DO UPDATE SET 
    status = EXCLUDED.status,
    home_score = EXCLUDED.home_score,
    away_score = EXCLUDED.away_score
RETURNING id
`

func (q *Queries) MatchFullTime(ctx context.Context, matchID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, matchFullTime, matchID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const rescheduleMatch = `-- name: RescheduleMatch :one
UPDATE matches
SET 
  match_date = $1,
  match_time = $2,
  updated_at = now()
WHERE id = $3 AND is_deleted = false
RETURNING id
`

type RescheduleMatchParams struct {
	MatchDate pgtype.Date `json:"match_date"`
	MatchTime pgtype.Time `json:"match_time"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) RescheduleMatch(ctx context.Context, arg *RescheduleMatchParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, rescheduleMatch, arg.MatchDate, arg.MatchTime, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const softDeleteTeams = `-- name: SoftDeleteTeams :one
UPDATE teams
SET is_deleted = true,
  deleted_at = now()
WHERE id = $1 AND is_deleted = false
RETURNING id
`

func (q *Queries) SoftDeleteTeams(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, softDeleteTeams, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const updatePlayers = `-- name: UpdatePlayers :one
UPDATE players
SET 
  team_id = COALESCE($1, team_id),
  name = COALESCE($2, name),
  height_cm = COALESCE($3, height_cm),
  weight_kg = COALESCE($4, weight_kg),
  position = COALESCE($5, position),
  jersey_number = COALESCE($6, jersey_number),
  updated_at = now()
WHERE id = $7 AND is_deleted = false
RETURNING id, team_id, name, height_cm, weight_kg, position, jersey_number, created_at, updated_at, is_deleted, deleted_at
`

type UpdatePlayersParams struct {
	TeamID       pgtype.UUID        `json:"team_id"`
	Name         pgtype.Text        `json:"name"`
	HeightCm     pgtype.Numeric     `json:"height_cm"`
	WeightKg     pgtype.Numeric     `json:"weight_kg"`
	Position     NullPlayerPosition `json:"position"`
	JerseyNumber pgtype.Int2        `json:"jersey_number"`
	ID           pgtype.UUID        `json:"id"`
}

func (q *Queries) UpdatePlayers(ctx context.Context, arg *UpdatePlayersParams) (*Player, error) {
	row := q.db.QueryRow(ctx, updatePlayers,
		arg.TeamID,
		arg.Name,
		arg.HeightCm,
		arg.WeightKg,
		arg.Position,
		arg.JerseyNumber,
		arg.ID,
	)
	var i Player
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.Name,
		&i.HeightCm,
		&i.WeightKg,
		&i.Position,
		&i.JerseyNumber,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return &i, err
}

const updateTeams = `-- name: UpdateTeams :one
UPDATE teams
SET 
  name = COALESCE($1, name),
  logo = COALESCE($2, logo),
  founded_year = COALESCE($3, founded_year),
  address = COALESCE($4, address),
  city = COALESCE($5, city),
  updated_at = now()
WHERE id = $6 AND is_deleted = false
RETURNING id, name, logo, founded_year, address, city, created_at, updated_at, is_deleted, deleted_at
`

type UpdateTeamsParams struct {
	Name        pgtype.Text `json:"name"`
	Logo        pgtype.Text `json:"logo"`
	FoundedYear pgtype.Text `json:"founded_year"`
	Address     pgtype.Text `json:"address"`
	City        pgtype.Text `json:"city"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateTeams(ctx context.Context, arg *UpdateTeamsParams) (*Team, error) {
	row := q.db.QueryRow(ctx, updateTeams,
		arg.Name,
		arg.Logo,
		arg.FoundedYear,
		arg.Address,
		arg.City,
		arg.ID,
	)
	var i Team
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Logo,
		&i.FoundedYear,
		&i.Address,
		&i.City,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IsDeleted,
		&i.DeletedAt,
	)
	return &i, err
}
