// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPlayerTeam = `-- name: CreatePlayerTeam :one
INSERT INTO players (
  team_id, name, height_cm, weight_kg, position, jersey_number
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id
`

type CreatePlayerTeamParams struct {
	TeamID       pgtype.UUID    `json:"team_id"`
	Name         string         `json:"name"`
	HeightCm     pgtype.Numeric `json:"height_cm"`
	WeightKg     pgtype.Numeric `json:"weight_kg"`
	Position     PlayerPosition `json:"position"`
	JerseyNumber int16          `json:"jersey_number"`
}

func (q *Queries) CreatePlayerTeam(ctx context.Context, arg *CreatePlayerTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createPlayerTeam,
		arg.TeamID,
		arg.Name,
		arg.HeightCm,
		arg.WeightKg,
		arg.Position,
		arg.JerseyNumber,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
  name, logo, founded_year, address, city
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id
`

type CreateTeamParams struct {
	Name        string      `json:"name"`
	Logo        pgtype.Text `json:"logo"`
	FoundedYear pgtype.Text `json:"founded_year"`
	Address     string      `json:"address"`
	City        string      `json:"city"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg *CreateTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Logo,
		arg.FoundedYear,
		arg.Address,
		arg.City,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getListTeams = `-- name: GetListTeams :many
SELECT id, name, logo, founded_year
FROM teams
ORDER BY founded_year DESC
`

type GetListTeamsRow struct {
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Logo        pgtype.Text `json:"logo"`
	FoundedYear pgtype.Text `json:"founded_year"`
}

func (q *Queries) GetListTeams(ctx context.Context) ([]*GetListTeamsRow, error) {
	rows, err := q.db.Query(ctx, getListTeams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*GetListTeamsRow{}
	for rows.Next() {
		var i GetListTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Logo,
			&i.FoundedYear,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTeams = `-- name: SoftDeleteTeams :exec
UPDATE teams
SET is_deleted = true,
  deleted_at = now()
WHERE id = $1
`

func (q *Queries) SoftDeleteTeams(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteTeams, id)
	return err
}
