// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package teamsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateTeam(ctx context.Context, arg *CreateTeamParams) (pgtype.UUID, error)
}

var _ Querier = (*Queries)(nil)
