// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package teamsdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTeam = `-- name: CreateTeam :one
INSERT INTO teams (
  name, logo, founded_year, address, city
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id
`

type CreateTeamParams struct {
	Name        string      `json:"name"`
	Logo        pgtype.Text `json:"logo"`
	FoundedYear pgtype.Text `json:"founded_year"`
	Address     string      `json:"address"`
	City        string      `json:"city"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg *CreateTeamParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createTeam,
		arg.Name,
		arg.Logo,
		arg.FoundedYear,
		arg.Address,
		arg.City,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
