// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "afrizalsebastian",
            "email": "sebastiangurning@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/hello": {
            "get": {
                "description": "Example API",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Example"
                ],
                "summary": "Example API -- Hello",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/api/v1/teams": {
            "get": {
                "description": "Get List Team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get List team",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-array_dto_GetListTeamItem"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new team",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Create Team",
                "parameters": [
                    {
                        "description": "Create team bory request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-dto_CreateTeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/api/v1/teams/{teamId}": {
            "delete": {
                "description": "Delete team (soft-delete)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Delete team (soft-delete)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    }
                }
            }
        },
        "/api/v1/teams/{teamId}/players": {
            "post": {
                "description": "Create a new team Player",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Create Team Player",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team ID",
                        "name": "teamId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create team bory request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreatePlayerTeamRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-dto_CreatePlayerTeamResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/api.WebResponse-any"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.ErrorsDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "field": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "api.WebResponse-any": {
            "type": "object",
            "properties": {
                "data": {},
                "error_message": {
                    "type": "string"
                },
                "errors_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ErrorsDetail"
                    }
                },
                "http_code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "message_code": {
                    "type": "integer"
                },
                "message_id": {
                    "type": "string"
                }
            }
        },
        "api.WebResponse-array_dto_GetListTeamItem": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GetListTeamItem"
                    }
                },
                "error_message": {
                    "type": "string"
                },
                "errors_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ErrorsDetail"
                    }
                },
                "http_code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "message_code": {
                    "type": "integer"
                },
                "message_id": {
                    "type": "string"
                }
            }
        },
        "api.WebResponse-dto_CreatePlayerTeamResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CreatePlayerTeamResponse"
                },
                "error_message": {
                    "type": "string"
                },
                "errors_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ErrorsDetail"
                    }
                },
                "http_code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "message_code": {
                    "type": "integer"
                },
                "message_id": {
                    "type": "string"
                }
            }
        },
        "api.WebResponse-dto_CreateTeamResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/dto.CreateTeamResponse"
                },
                "error_message": {
                    "type": "string"
                },
                "errors_detail": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.ErrorsDetail"
                    }
                },
                "http_code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "message_code": {
                    "type": "integer"
                },
                "message_id": {
                    "type": "string"
                }
            }
        },
        "dto.CreatePlayerTeamRequest": {
            "type": "object",
            "required": [
                "Position",
                "height",
                "jersey_number",
                "name",
                "weight"
            ],
            "properties": {
                "Position": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "jersey_number": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "dto.CreatePlayerTeamResponse": {
            "type": "object",
            "properties": {
                "Position": {
                    "type": "string"
                },
                "height": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "jersey_number": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "team_id": {
                    "type": "string"
                },
                "weight": {
                    "type": "number"
                }
            }
        },
        "dto.CreateTeamRequest": {
            "type": "object",
            "required": [
                "address",
                "city",
                "founded_year",
                "logo",
                "name"
            ],
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "founded_year": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.CreateTeamResponse": {
            "type": "object",
            "properties": {
                "address": {
                    "type": "string"
                },
                "city": {
                    "type": "string"
                },
                "founded_year": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "dto.GetListTeamItem": {
            "type": "object",
            "properties": {
                "founded_year": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "logo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "API Football Team Management",
	Description:      "API Spec for footbal team management",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
